### ISSUE TITLE
Add a button to increment/decrement font size

### ISSUE THREAD

**Issue by DjebbZ** [jsofra/data-scope#4]
Hello,

First of all, thank you for the project, we're using it almost everyday, the inspector is extremely useful.

I've just tried to look at how to implement a button to increment/decrement font-size of the inspector macro `#ds/i`, so that it's more readable in my small laptops screen. At first sight it would mean duplicating some code of `clojure.inspector` into data-scope itself then adding a button that change the `Font`. I tried looking into the details but got lost in the huge class hierarchy of Java.awt/swing etc. I'm not a Java developer, so I'm struggling to follow the mess.

Would you mind implementing it for me (and others of course) pretty please ?

Thanks a lot in advance.

PS : if you really don't want to implement it yourself, could I have instead some guidance wrt how to do it ?

**Comment by jsofra** [comment]
Hi,

I like the idea! I have added this to the latest SNAPSHOT version. You can check it out and have a look, "0.1.3-SNAPSHOT". If if works well for you then I will document it and cut a new release some time soon.

The font size that you set with the buttons will persist in an atom. You may set this manually if you wish `(reset! data-scope.inspect/ds-i-font-size 20)`.

**Comment by DjebbZ** [comment]
Thanks a lot ! I will try on Wednesday when I get back to my computer and
give you feedback.

**Comment by DjebbZ** [comment]
I just tried locally with a very simple map : it's exactly what I wanted ! Thanks a lot !

If you want I can report tomorrow with real data at work.

**Comment by DjebbZ** [comment]
Tried it, works like a charm.

A suggestion : add a label to the buttons. I would add the text `Font size` between the 2 buttons `+` and `-` but it's up to you.

Thanks again !

**Comment by DjebbZ** [comment]
Closing, the suggested label isn't important. Thanks again (again haha).
